apiVersion: v1
kind: Pod
metadata:
  name: rhacm-monitor-backend
  namespace: rhacm-monitor
  labels:
    app: rhacm-monitor
    component: backend
spec:
  serviceAccountName: rhacm-monitor
  containers:
  - name: backend
    image: registry.access.redhat.com/ubi9/ubi-minimal:latest
    command: ["/server"]
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    env:
    - name: PORT
      value: "8080"
    - name: ENABLE_AUTH
      value: "false"
    - name: LOG_LEVEL
      value: "info"
    volumeMounts:
    - name: server-binary
      mountPath: /server
      subPath: server
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 256Mi
  volumes:
  - name: server-binary
    emptyDir: {}
  initContainers:
  - name: copy-binary
    image: registry.access.redhat.com/ubi9/ubi:latest
    command:
    - sh
    - -c
    - |
      echo "Binary will be copied here"
      sleep infinity
    volumeMounts:
    - name: server-binary
      mountPath: /tmp/server-mount

