apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhacm-monitor-backend
  namespace: rhacm-monitor
  labels:
    app: rhacm-monitor
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rhacm-monitor
      component: backend
  template:
    metadata:
      labels:
        app: rhacm-monitor
        component: backend
    spec:
      serviceAccountName: rhacm-monitor
      containers:
      - name: backend
        image: quay.io/bzhai/rhacm-monitor-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: PORT
          value: "8080"
        - name: ENABLE_AUTH
          value: "true"
        - name: OAUTH_ISSUER_URL
          value: "https://kubernetes.default.svc"
        - name: LOG_LEVEL
          value: "info"
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /api/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true

