apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhacm-monitor

resources:
- namespace.yaml
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- backend-deployment.yaml
- backend-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- route.yaml

commonLabels:
  app: rhacm-monitor

images:
- name: quay.io/bzhai/rhacm-monitor-backend
  newTag: latest
- name: quay.io/bzhai/rhacm-monitor-frontend
  newTag: latest

