apiVersion: apps.redhat.com/v1alpha1
kind: RHACMMonitor
metadata:
  name: rhacm-monitor
  namespace: rhacm-monitor
spec:
  backend:
    image: quay.io/rhacm-monitor/backend:latest
    replicas: 2
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    enableAuth: true
  frontend:
    image: quay.io/rhacm-monitor/frontend:latest
    replicas: 2
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
  route:
    enabled: true
    host: rhacm-monitor.apps.example.com
    tlsEnabled: true

