apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rhacmmonitors.apps.redhat.com
spec:
  group: apps.redhat.com
  names:
    kind: RHACMMonitor
    listKind: RHACMMonitorList
    plural: rhacmmonitors
    singular: rhacmmonitor
    shortNames:
    - rhacmmon
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: RHACMMonitor is the Schema for the rhacmmonitors API
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object.'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents.'
            type: string
          metadata:
            type: object
          spec:
            description: RHACMMonitorSpec defines the desired state of RHACMMonitor
            type: object
            properties:
              backend:
                description: Backend configuration
                type: object
                properties:
                  image:
                    type: string
                    default: "quay.io/rhacm-monitor/backend:latest"
                  replicas:
                    type: integer
                    default: 2
                  resources:
                    type: object
                    properties:
                      limits:
                        type: object
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                      requests:
                        type: object
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                  enableAuth:
                    type: boolean
                    default: true
              frontend:
                description: Frontend configuration
                type: object
                properties:
                  image:
                    type: string
                    default: "quay.io/rhacm-monitor/frontend:latest"
                  replicas:
                    type: integer
                    default: 2
                  resources:
                    type: object
                    properties:
                      limits:
                        type: object
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                      requests:
                        type: object
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
              route:
                description: Route configuration
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: true
                  host:
                    type: string
                  tlsEnabled:
                    type: boolean
                    default: true
          status:
            description: RHACMMonitorStatus defines the observed state of RHACMMonitor
            type: object
            properties:
              conditions:
                description: Conditions represent the latest available observations of an object's state
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              phase:
                description: Phase represents the current phase of the deployment
                type: string
                enum:
                - Pending
                - Installing
                - Running
                - Failed
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp

