apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhacm-monitor-frontend
  namespace: rhacm-monitor
  labels:
    app: rhacm-monitor
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rhacm-monitor
      component: frontend
  template:
    metadata:
      labels:
        app: rhacm-monitor
        component: frontend
    spec:
      containers:
      - name: frontend
        image: quay.io/bzhai/rhacm-monitor-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true

